#!/usr/bin/env bash
# deploy/bootstrap.sh — bring up the traceback-coach lab on a fresh Ubuntu VM.
#
# Idempotent: safe to re-run. Run from the repo's deploy/ directory as root
# (or with sudo). It does NOT clone the repo and does NOT touch Cloudflare —
# those are done separately (see deploy/README.md).
#
# Required inputs (env vars; the script refuses to run without them):
#   TUNNEL_TOKEN      Cloudflare named-tunnel token (from the Zero Trust dashboard)
#   PUBLIC_HOSTNAME   the public hostname served by the tunnel, e.g. lab.example.com
#   JUPYTER_PASSWORD  a strong plaintext password (hashed here; never stored in plaintext)
#
# Example:
#   TUNNEL_TOKEN=... PUBLIC_HOSTNAME=lab.example.com JUPYTER_PASSWORD='...' \
#     bash deploy/bootstrap.sh
set -euo pipefail

cd "$(dirname "$0")"   # run from deploy/

# ── 0. Preconditions ────────────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
  echo "Please run as root (or with sudo)." >&2
  exit 1
fi
: "${TUNNEL_TOKEN:?set TUNNEL_TOKEN (Cloudflare tunnel token)}"
: "${PUBLIC_HOSTNAME:?set PUBLIC_HOSTNAME (e.g. lab.example.com)}"
: "${JUPYTER_PASSWORD:?set JUPYTER_PASSWORD (a strong password you will type in the lab)}"

# ── 1. Docker Engine + compose plugin ───────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  echo "==> Installing Docker..."
  curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker >/dev/null 2>&1 || true

# ── 2. Hash the Jupyter password with argon2 (throwaway container) ───────────
echo "==> Hashing the Jupyter password (argon2id)..."
HASH=$(docker run --rm -e P="$JUPYTER_PASSWORD" python:3.12-slim sh -c \
  'pip -q install "jupyter-server>=2" argon2-cffi >/dev/null 2>&1 && \
   python -c "import os; from jupyter_server.auth import passwd; print(passwd(os.environ[\"P\"]))"')
case "$HASH" in
  argon2:*) : ;;
  *) echo "Password hashing failed (got: ${HASH:0:16}...)." >&2; exit 1 ;;
esac

# ── 3. Write deploy/.env (secrets only here, perms 600, never committed) ─────
echo "==> Writing .env (chmod 600)..."
# Escape every '$' as '$$' so Docker Compose does not interpolate the argon2
# hash (it is full of $argon2id$v=19$m=... segments). Compose turns $$ back
# into a literal $ when it passes the value to the container.
HASH_ESC=${HASH//\$/\$\$}
umask 077
cat > .env <<EOF
# Generated by bootstrap.sh — DO NOT COMMIT. Contains live secrets.
TUNNEL_TOKEN=${TUNNEL_TOKEN}
PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
JUPYTER_PASSWORD_HASH=${HASH_ESC}
EOF
chmod 600 .env

# ── 4. Build + run the stack ────────────────────────────────────────────────
echo "==> Building and starting the stack..."
docker compose up -d --build

echo
echo "==> Status:"
docker compose ps
echo
echo "Done. The lab container has NO published host ports (cloudflared reaches it"
echo "internally). Check the tunnel with:  docker compose logs -f cloudflared"
echo "Then open:  https://${PUBLIC_HOSTNAME}"
